package com.example.student;
import com.example.UserRole;
import javax.swing.*;
import java.awt.*;

import com.example.Check;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

public class Register {
    //    private JPanel panel;
//    private JTextField textUsername;
//    private JPasswordField textPassword;
//    private JComboBox<UserRole> comboRole;
    private JButton registerButton;
    private JComboBox comboRole;
    private JPanel panel;
    private JTextField textUsername;
    private JPasswordField textPassword;

    public Register() {
        comboRole.addItem(UserRole.STUDENT);
        comboRole.addItem(UserRole.TEACHER);
        comboRole.addItem(UserRole.ADMIN);
        registerButton.addActionListener(e -> {
            String username = textUsername.getText();
            String password = new String(textPassword.getPassword());
            System.out.printf("Register get username %s password %s\n",username,password);
            UserRole role = (UserRole) comboRole.getSelectedItem();
            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(panel, "enter username and password!");
                return;
            }
            Check check = new Check();
            boolean result = check.register(username, password, role);
            if (result) {
                if(role!=null)
                {
                    JOptionPane.showMessageDialog(panel, String.format("Register successful user %s role %s!",username,role.name()));
                }
                textUsername.setText("");
                textPassword.setText("");
            } else {
                JOptionPane.showMessageDialog(panel, "Username already exists!");
            }
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(panel);
            frame.dispose();
        });
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        comboRole = new JComboBox();
        panel.add(comboRole, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textUsername = new JTextField();
        panel.add(textUsername, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textPassword = new JPasswordField();
        panel.add(textPassword, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        registerButton = new JButton();
        registerButton.setText("Button");
        panel.add(registerButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}